server:


  port: 8081
  servlet:                  # ğŸ”¥ æ–°å¢è¿™ä¸€è¡Œ
    context-path: /zzuvisitor # ğŸ”¥ æ–°å¢è¿™ä¸€è¡Œ



#æ•°æ®åº“é…ç½®

spring:
  datasource:
    #alibabaæ•°æ®è¿æ¥æ± 
    type: com.alibaba.druid.pool.DruidDataSource
    #postgresqlé©±åŠ¨
    driverClassName: org.postgresql.Driver
    #æ•°æ®åº“åœ°å€ã€è´¦å·ã€å¯†ç 
    url: jdbc:postgresql://127.0.0.1:5432/postgres?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: postgres
    password: 123456
    druid:
      #åˆå§‹åŒ–è¿æ¥å¤§å°
      initial-size: 8
      #æœ€å°ç©ºé—²è¿æ¥æ•°
      min-idle: 5
      #æœ€å¤§è¿æ¥æ•°
      max-active: 10
      #æŸ¥è¯¢è¶…æ—¶æ—¶é—´
      query-timeout: 6000
      #äº‹åŠ¡æŸ¥è¯¢è¶…æ—¶æ—¶é—´
      transaction-query-timeout: 6000
      #å…³é—­ç©ºé—²è¿æ¥è¶…æ—¶æ—¶é—´
      remove-abandoned-timeout: 1800
      filters: stat,config



mybatis:
  # æ‰«æè‡ªå®šä¹‰TypeHandleråŒ…
  type-handlers-package: com.campus.vistorservice.handler


  #sqlæ˜ å°„æ–‡ä»¶

  mapper-locations: classpath:mapper/*.xml

  #model

  #   type-aliases-package: com.campus.vistorservice.model
  #   type-handlers-package: com.campus.vistorservice.mybatis  # æ–°å¢ï¼šæ‰«æç±»å‹å¤„ç†å™¨

  configuration:
    # å¼€å¯é©¼å³°å‘½åè‡ªåŠ¨è½¬æ¢
    map-underscore-to-camel-case: true
    # æ˜¾ç¤ºSQLæ—¥å¿—
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





